"""initial migration

Revision ID: c75f4ff57f55
Revises: 
Create Date: 2026-09-15 06:16:57.946871
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c75f4ff57f55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_activity_log_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_activity_log_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_activity_log_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_table('admin_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_admin_roles_name'))
    )
    op.create_table('business',
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_business_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_business_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_business_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business'))
    )
    op.create_table('business_branch',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('inventory_software_business_branch_id', sa.String(length=255), nullable=True),
    sa.Column('inventory_software_api_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('inventory_synced', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inventory_sync_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_business_branch_business_id_business'), use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_business_branch_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_business_branch_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_business_branch_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_branch'))
    )
    op.create_table('staff_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_staff_roles_name'))
    )
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.String(length=2048), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('admin_role_id', sa.Uuid(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_role_id'], ['admin_roles.id'], name=op.f('fk_admins_admin_role_id_admin_roles')),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], name='fk_admins_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], name='fk_admins_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('username', name=op.f('uq_admins_username'))
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('business_image',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_cover', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['business_branch.id'], name=op.f('fk_business_image_branch_id_business_branch')),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_business_image_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_business_image_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_business_image_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_image'))
    )
    op.create_table('business_setting',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('service_charge_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('booking_expiration_minutes', sa.Integer(), nullable=True),
    sa.Column('allow_partial_payment', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['business_branch.id'], name=op.f('fk_business_setting_branch_id_business_branch')),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_business_setting_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_business_setting_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_business_setting_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_setting')),
    sa.UniqueConstraint('branch_id', name=op.f('uq_business_setting_branch_id'))
    )
    op.create_table('staff',
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('staff_role_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['business_branch.id'], name=op.f('fk_staff_branch_id_business_branch'), use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_staff_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_staff_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['staff_role_id'], ['staff_roles.id'], name=op.f('fk_staff_staff_role_id_staff_roles')),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_staff_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff')),
    sa.UniqueConstraint('email', name=op.f('uq_staff_email'))
    )
    op.create_table('admin_logins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('browser', sa.String(length=200), nullable=True),
    sa.Column('operating_system', sa.String(length=200), nullable=True),
    sa.Column('login_status', sa.String(length=50), nullable=False, comment='SUCCESS, FAILED, LOGOUT, TOKEN_REFRESH'),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=2048), nullable=True),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_admin_logins_admin_id_admins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_logins'))
    )
    op.create_index(op.f('ix_admin_logins_admin_id'), 'admin_logins', ['admin_id'], unique=False)
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_audit_trail_staff_id_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_trail'))
    )
    op.create_table('staff_login',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_staff_login_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_staff_login_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_staff_login_staff_id_staff')),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_staff_login_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_login'))
    )
    op.create_table('staff_onboarding',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('personal_information', sa.JSON(), nullable=False),
    sa.Column('employment_information', sa.JSON(), nullable=False),
    sa.Column('emergency_contact', sa.JSON(), nullable=False),
    sa.Column('identification', sa.JSON(), nullable=False),
    sa.Column('bank_information', sa.JSON(), nullable=False),
    sa.Column('next_of_kin', sa.JSON(), nullable=False),
    sa.Column('skills_and_qualifications', sa.JSON(), nullable=False),
    sa.Column('family_background', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('reference_verification', sa.JSON(), nullable=False),
    sa.Column('declaration', sa.JSON(), nullable=False),
    sa.Column('hr_use_only', sa.JSON(), nullable=False),
    sa.Column('onboarding_status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_staff_onboarding_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_staff_onboarding_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_staff_onboarding_staff_id_staff')),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_staff_onboarding_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_onboarding')),
    sa.UniqueConstraint('staff_id', name=op.f('uq_staff_onboarding_staff_id'))
    )
    op.create_table('task',
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff.id'], name=op.f('fk_task_assigned_staff_id_staff')),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_task_created_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.id'], name=op.f('fk_task_deleted_by_staff'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.id'], name=op.f('fk_task_updated_by_staff'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('staff_onboarding')
    op.drop_table('staff_login')
    op.drop_table('audit_trail')
    op.drop_index(op.f('ix_admin_logins_admin_id'), table_name='admin_logins')
    op.drop_table('admin_logins')
    op.drop_table('staff')
    op.drop_table('business_setting')
    op.drop_table('business_image')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('staff_roles')
    op.drop_table('business_branch')
    op.drop_table('business')
    op.drop_table('admin_roles')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
